travis:
  secure:
    BINSTAR_TOKEN: B5N5zYRkKLlDFEzyJFtp6fEIEDp2tI64/1I+HkRGj7uAPCShgTlyhd1rNMhdhhgYD1wwz4keywgzL/ea3mHo4bI55AtXEPRD3+JpQ/G29CrI1+6pGEK3uUuWmlsZk3EIb6Pnw68d07lDmm8Jt/9pDFgNJuoK4yD+lYN3tPZUBkD7Gajx4aMwwYdTI5Xc/1m6spppXQeCm2/e2nYQDmsuD4dndQTz46yo/gGV352TW0jfTGEeIyprj89SLMPWNDr2EoZrBiS+UoQbZt9mzjcLcZ68zs0NCr4fKpaKXeXFwTBhIqzKLivg1OJ8AGLvjVx8Q8W62XeCRedNIbLtkVidvK40VY2RZd9Se3x6cbz/awC/x/2TAMuMk1C6FoYIA/idNAaIqxzYPvgtF48FZw+Mc15kFOy6uZuipUXgbsbLdDedSW2Gxf5Y9rlEE0fk6Klh2Tgxyzu+GrTLSUFAAmyD4HJ5pXCzX6+erBe7TLD2Wdsv0vyFY73rWk4BJIk49dX5oYtnpnDeeyo/HCqH5OHxBVRLVPfpKcpwtrOcKtjCwRgar3J3wyt1htYjnssPCiT6n0V6u6HTVetU9kqEURkslaK1FThhlv6UMLzgWhSlbButMJfr9sV+iN/b32q+wqRkiqgOllJ1qvxZho1k/umhjrBYGuor7mZJNmvVxm7DkWE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
